### ISSUE TITLE
chown pas automatique

### ISSUE THREAD

**Issue by arnouxor** [maltyxx/docker-sshd#1]
Bonjour M. Malty Xx

Quand on monte un volume : /home/user/www 
cela crée le répertoire www avec les droits root:root et non pas 1001:1001 (par exemple)

du coup on est obligé de se connecter au serveur et de faire un chown

**Comment by maltyxx** [comment]
Je cloture ce ticket car par défaut le chown est automatiquement sur la nouvelle version. ;)
