### ISSUE TITLE
Change host key permissions

### ISSUE THREAD

**Issue by pwFoo** [maltyxx/docker-sshd#2]
Doesn't work for me with generated host key:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/etc/ssh/ssh_host_ecdsa_key' are too open.
It is recommended that your private key files are NOT accessible by others.
This private key will be ignored.
key_load_private: bad permissions
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
```

**Comment by pwFoo** [comment]
Any update?
ssh won't work with wrong permissions.

**Comment by maltyxx** [comment]
Thanks for update your container with the command: 
$ pull maltyxx/sshd:latest
We changed the volume containing the configuration: /usr/local/etc/sshd and not /etc/ssh

**Comment by pwFoo** [comment]
Hi @maltyxx.
I tested it with docker @ windows and there war a problem will image pull...
After pull the latest it works fine again! Thanks!
