### ISSUE TITLE
Set login shell to users

### ISSUE THREAD

**Issue by pwFoo** [maltyxx/docker-sshd#3]
Users added by cmd should be able to login.
Existing users with shell "/sbin/nologin" can't login (for example www-data).

**Comment by pwFoo** [comment]
It doesn't work if the used uid exists. A second user is added, but login fails because of the first existing user I think?

**Comment by maltyxx** [comment]
I don't understand, but if you disable the ssh login :
Add custom volume /usr/local/etc/sshd/ in the file

/usr/local/etc/sshd/sshd_config

# Force sftp and chroot jail
Subsystem sftp internal-sftp
ForceCommand internal-sftp
ChrootDirectory %h

**Comment by maltyxx** [comment]
Show me your config docker-compose.yml or the command ?

**Comment by pwFoo** [comment]
After pull latest image it seems to work.

I use uid 33 (which is equal to the existing www-data user). Pulled latest and started a clean container with uid 33 and login works fine! I think it's fixed. Thanks!
